version: '3.9'

services:
  mongo:
    container_name: mongo-sql-migration-poc
    image: 'mongo:4.2.19'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
